# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{gwt_rpc}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Andrew Carpenter"]
  s.date = %q{2011-11-18}
  s.description = %q{Spider Google Web Toolkit sites using ruby}
  s.email = %q{andrew.main@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "gwt_rpc.gemspec",
    "lib/gwt_rpc.rb",
    "lib/gwt_rpc/base_extensions/array.rb",
    "lib/gwt_rpc/base_extensions/boolean.rb",
    "lib/gwt_rpc/base_extensions/date.rb",
    "lib/gwt_rpc/base_extensions/fixnum.rb",
    "lib/gwt_rpc/base_extensions/float.rb",
    "lib/gwt_rpc/base_extensions/hash.rb",
    "lib/gwt_rpc/base_extensions/multipart_string.rb",
    "lib/gwt_rpc/base_extensions/string.rb",
    "lib/gwt_rpc/client.rb",
    "lib/gwt_rpc/gxt/hash.rb",
    "lib/gwt_rpc/gxt/paginated_resultset.rb",
    "lib/gwt_rpc/gxt/sort_dir.rb",
    "lib/gwt_rpc/gxt/sort_info.rb",
    "lib/gwt_rpc/procedure.rb",
    "lib/gwt_rpc/request.rb",
    "lib/gwt_rpc/response.rb",
    "lib/gwt_rpc/response/reader.rb",
    "spec/gwt_rpc/base_extensions/array_spec.rb",
    "spec/gwt_rpc/base_extensions/boolean_spec.rb",
    "spec/gwt_rpc/base_extensions/hash_spec.rb",
    "spec/gwt_rpc/base_extensions/multipart_string_spec.rb",
    "spec/gwt_rpc/base_extensions/string_spec.rb",
    "spec/gwt_rpc/client_spec.rb",
    "spec/gwt_rpc/gxt/hash_spec.rb",
    "spec/gwt_rpc/gxt/paginated_resultset_spec.rb",
    "spec/gwt_rpc/gxt/sort_dir_spec.rb",
    "spec/gwt_rpc/gxt/sort_info_spec.rb",
    "spec/gwt_rpc/procedure_spec.rb",
    "spec/gwt_rpc/request_spec.rb",
    "spec/gwt_rpc/response/reader_spec.rb",
    "spec/gwt_rpc/response_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/andrewcarpenter/gwt_rpc}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.2}
  s.summary = %q{Ruby Google Web Toolkit client}
  s.test_files = [
    "spec/gwt_rpc/base_extensions/array_spec.rb",
    "spec/gwt_rpc/base_extensions/boolean_spec.rb",
    "spec/gwt_rpc/base_extensions/hash_spec.rb",
    "spec/gwt_rpc/base_extensions/multipart_string_spec.rb",
    "spec/gwt_rpc/base_extensions/string_spec.rb",
    "spec/gwt_rpc/client_spec.rb",
    "spec/gwt_rpc/gxt/hash_spec.rb",
    "spec/gwt_rpc/gxt/paginated_resultset_spec.rb",
    "spec/gwt_rpc/gxt/sort_dir_spec.rb",
    "spec/gwt_rpc/gxt/sort_info_spec.rb",
    "spec/gwt_rpc/procedure_spec.rb",
    "spec/gwt_rpc/request_spec.rb",
    "spec/gwt_rpc/response/reader_spec.rb",
    "spec/gwt_rpc/response_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<typhoeus>, [">= 0"])
      s.add_runtime_dependency(%q<activesupport>, [">= 0"])
      s.add_runtime_dependency(%q<json>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["> 2.0.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.1"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_runtime_dependency(%q<typhoeus>, [">= 0"])
      s.add_runtime_dependency(%q<activesupport>, [">= 0"])
      s.add_runtime_dependency(%q<json>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["> 1.2.3"])
    else
      s.add_dependency(%q<typhoeus>, [">= 0"])
      s.add_dependency(%q<activesupport>, [">= 0"])
      s.add_dependency(%q<json>, [">= 0"])
      s.add_dependency(%q<rspec>, ["> 2.0.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<typhoeus>, [">= 0"])
      s.add_dependency(%q<activesupport>, [">= 0"])
      s.add_dependency(%q<json>, [">= 0"])
      s.add_dependency(%q<rspec>, ["> 1.2.3"])
    end
  else
    s.add_dependency(%q<typhoeus>, [">= 0"])
    s.add_dependency(%q<activesupport>, [">= 0"])
    s.add_dependency(%q<json>, [">= 0"])
    s.add_dependency(%q<rspec>, ["> 2.0.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<typhoeus>, [">= 0"])
    s.add_dependency(%q<activesupport>, [">= 0"])
    s.add_dependency(%q<json>, [">= 0"])
    s.add_dependency(%q<rspec>, ["> 1.2.3"])
  end
end

